Release the display text texture
streamlabs/obs-studio-node pull request #236
Opened 2019-01-29 19:44 UTC by RodrigoHolztrattner

2019-02-08 01:40 UTC, EddyGharbi requested changes

2019-02-08 01:40 UTC, eddyStreamlabs commented on obs-studio-server/source/nodeobs_display.cpp
> +
Please correct indentation here.

2019-02-08 17:27 UTC, RodrigoHolztrattner commented on obs-studio-server/source/nodeobs_display.cpp
> +
Done!

2019-02-11 17:55 UTC, eddyStreamlabs commented on obs-studio-server/source/nodeobs_display.cpp
> +
I still see the same issue.

2019-02-11 18:35 UTC, RodrigoHolztrattner commented on obs-studio-server/source/nodeobs_display.cpp
> +
I think now it's fixed

2019-02-13 22:09 UTC, eddyStreamlabs commented on obs-studio-server/source/nodeobs_display.cpp
> +
Looks good ty

2019-02-13 22:10 UTC, merged